# Generated by Django 2.0.6 on 2018-09-29 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='text',
            field=models.TextField(default='Some string'),
        ),
        migrations.AddField(
            model_name='test',
            name='title',
            field=models.CharField(default='Some string', max_length=200),
        ),
    ]
